weights: last.pt
cfg: models/yolov5n-0.5.yaml
data: data/rm.yaml
hyp: data/hyp.scratch.yaml
epochs: 300
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: true
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: true
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 4
project: runs/train
name: exp
exist_ok: false
total_batch_size: 16
world_size: 1
global_rank: -1
save_dir: runs/train/exp2
